import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/navbar";
import Slider from "@/components/slider";
import Prices from "@/components/prices"
import React, { useState, useEffect} from 'react'
import ContactPage from "@/components/contactPage"
import Footer from "@/components/footer";
import Promotion from "@/components/promotion";

export default function Home() {
var sidebar = false;

const [sidebarOpen, setSidebarOpen] = useState(false);

const toggleSidebar = () => {
  setSidebarOpen(!sidebarOpen);
};

  return (
    <>
      <Head>
        <title>Espace Coiffure Le Trait</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="home" className={styles.main}>
        <div>
          <Nav></Nav>
          <hr className="promotion-hr" />
          <Promotion></Promotion>
        </div>
        <div className="swiper-container">
           <Slider></Slider>
        </div>
        <div className="full-width bg-black text-white">
          <Prices></Prices> 
          <ContactPage></ContactPage>
          <footer>
            <Footer></Footer>
          </footer>
        </div>
      </main>
    </>
  );
}
