import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/navbar";
import Slider from "@/components/slider";
import Prices from "@/components/prices"
import React, { useState, useEffect} from 'react'

export default function Home() {
var sidebar = false;

const [sidebarOpen, setSidebarOpen] = useState(false);

const toggleSidebar = () => {
  setSidebarOpen(!sidebarOpen);
};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Nav></Nav>
        </div>
        <div className="swiper-container">
           <Slider></Slider>
        </div>
        <Prices></Prices>
      </main>
    </>
  );
}
